personium/api-references

- api/ja/293_OAuth2_Token_Endpoint.md
- api_html/en/293_OAuth2_Token_Endpoint.html
- api_html/ja/293_OAuth2_Token_Endpoint.html
* Delete unnecessary information of Restriction
* Change heading size of Request
* Correction of cURL sample notation of Refresh token authentication
> Correct typographical error of Token Endpoint API

- api_html/en/212_Create_Account.html
> Rewrite specification of name

- api/en/000_Rest_API_Reference.md
- api/ja/000_Rest_API_Reference.md
ja/000_Rest_API_Reference.md
en/000_Rest_API_Reference.md
> Change the　align of the table (#54)

- api/en/283_Log_File_Information_Acquisition.md
- api/en/284_Retrieve_Log_File_list.md
- api/en/289_Cell_ACL.md
- api/en/290_Cell_Get_Property.md
- api/en/293_OAuth2_Token_Endpoint.md
- api/en/305_Get_Property.md
- api/en/306_Create_Collection.md
- api/en/307_Get_Property.md
- api/en/308_Change_Property.md
- api/en/313_Change_Property.md
- api/en/315_Configure_Access_Control.md
- api/en/371_Get_Schema.md
- api/en/380_Configure_Service_Collection.md
- api/en/505_Get_Property_Snapshot_Cell.md
- api/ja/283_Log_File_Information_Acquisition.md
- api/ja/284_Retrieve_Log_File_list.md
- api/ja/289_Cell_ACL.md
- api/ja/290_Cell_Get_Property.md
- api/ja/293_OAuth2_Token_Endpoint.md
- api/ja/305_Get_Property.md
- api/ja/306_Create_Collection.md
- api/ja/307_Get_Property.md
- api/ja/308_Change_Property.md
- api/ja/313_Change_Property.md
- api/ja/315_Configure_Access_Control.md
- api/ja/371_Get_Schema.md
- api/ja/380_Configure_Service_Collection.md
- api/ja/505_Get_Property_Snapshot_Cell.md
Eliminate link text conversion of "urn:x-personium:xmlns".  (#81) 
Correction of response sample.  (/en/290_Cell_Get_Property.md)
> Modification of hyperlink description (#81)

- api/en/293_OAuth2_Token_Endpoint.md
- api/ja/293_OAuth2_Token_Endpoint.md
293_OAuth2_Token_Endpoint.html) (en/ja)
> Change to the word "refresh_token"  (#76)

- api/en/248_Update_External_Role.md
/en/248_Update_External_Role.md
> Correction of mistakes

- api/en/289_Cell_ACL.md
- api/ja/289_Cell_ACL.md
This PR is related to #98.
289_Cell_ACL.md (ja/en) were changed.
> Add rule privileges.

- api/en/000_Rest_API_Reference.md
- api/en/101_List_Cell.md
000_Rest_API_Reference.md
101_List_Cell.md
> Additional correction (#83)

- api/en/504_Get_Snapshot_Cell.md
- api/ja/104_Delete_Cell.md
- api/ja/217_Register_Account_links.md
- api/ja/218_Acquire_Account_links_List.md
- api/ja/504_Get_Snapshot_Cell.md
ja/en 
•504_Get_Snapshot_Cell
ja/
•104_Delete_Cell
•217_Register_Account_links
•218_Acquire_Account_links_List
> Modifying the cURL sample and add line break (#109 & #110)

- api/ja/211_List_Using_Role_NavProp.md
- api/ja/254_Register_Using_Role_NavProp.md
- api/ja/255_List_External_Role_NavProp.md
ja\211_List_Using_Role_NavProp
ja\254_Register_Using_Role_NavProp
ja\255_List_External_Role_NavProp.md
> Change the description of NavProp (#84)

- api/en/000_Rest_API_Reference.md
- api/ja/000_Rest_API_Reference.md
Target files
000_Rest_API_Reference.html (ja/en)
> Fix mistakes (#114)

- api/en/267_Received_Message_Approval.md
- api/ja/267_Received_Message_Approval.md
Need rule privilege when RequestType is rule.add or rule.remove.
> Add required privilege in 267_Received_Message_Approval.md.

- api/en/2A0_Create_Rule.md
- api/ja/2A0_Create_Rule.md
> Add relay.event Action in 2A0_Create_Rule.md.

- api/en/2A0_Create_Rule.md
- api/ja/2A0_Create_Rule.md
> Update EventInfo and EventObject in 2A0_Create_Rule.md.

- api/en/277_Event_Summary.md
- api/en/2A0_Create_Rule.md
- api/ja/277_Event_Summary.md
- api/ja/2A0_Create_Rule.md
Modify as follows:
```
https://xxx -> https&#58;//xxx
```
Add link to 277_Event_Summary.md in order to refer EventType on 2A0_Create_Rule.md.
> Don't convert URL string to link.

- api/en/277_Event_Summary.md
- api/en/2A0_Create_Rule.md
- api/ja/277_Event_Summary.md
- api/ja/2A0_Create_Rule.md
This PR is related to personium/personium-core#177.
> Update 2A0_Create_Rule.md and 277_Event_Summary.md.

- api/en/278_Event_Reception.md
- api/en/293_OAuth2_Token_Endpoint.md
278_Event_Reception.md
293_OAuth2_Token_Endpoint.md
> Correction of English version (#135)

- api/en/207_List_Role_links.md
- api/en/218_Acquire_Account_links_List.md
- api/en/229_List_External_Cell_links.md
- api/en/240_List_Relation_links.md
- api/en/251_Retrieve_External_Role_links.md
- api/en/262_List_Box_links.md
- api/en/2A6_List_Rule_links.md
- api/en/324_List_AssociationEnd_links.md
- api/en/333_List_ComplexType_links.md
- api/en/351_List_EntityType_links.md
- api/en/361_List_Property_links.md
- api/en/374_User_Data_List_links.md
- api/ja/207_List_Role_links.md
- api/ja/218_Acquire_Account_links_List.md
- api/ja/229_List_External_Cell_links.md
- api/ja/240_List_Relation_links.md
- api/ja/251_Retrieve_External_Role_links.md
- api/ja/262_List_Box_links.md
- api/ja/2A6_List_Rule_links.md
- api/ja/324_List_AssociationEnd_links.md
- api/ja/333_List_ComplexType_links.md
- api/ja/351_List_EntityType_links.md
- api/ja/361_List_Property_links.md
- api/ja/374_User_Data_List_links.md
Left only [top query] and [skip query] and commented out other queries.
> Changing the request query (#143)

- api/en/271_Send_Message.md
- api/en/277_Event_Summary.md
- api/en/2A0_Create_Rule.md
- api/ja/271_Send_Message.md
- api/ja/277_Event_Summary.md
- api/ja/2A0_Create_Rule.md
This PR is related to personium/personium-core#199 and personium/personium-core#201.
> Update event related files.

- api/en/2A0_Create_Rule.md
- api/ja/2A0_Create_Rule.md
> Fix unnecessary links  (#153)

- api/en/002_CORS_Support.md
- api/ja/002_CORS_Support.md
> BUGFIX: Wrong mistake

- api/en/000_Rest_API_Reference.md
- api/ja/000_Rest_API_Reference.md
> Correspondence of #167

- api/en/000_Rest_API_Reference.md
> Correction omission correspondence.

- api/en/004_Error_Messages.md
- api/ja/004_Error_Messages.md
Error code `PR400-AZ-0007` is defined as `BOX_NOT_INSTALLED`:
https://github.com/personium/personium-core/blob/ca373588348ce12bed50a70de032720b2c3d2ab0/src/main/java/io/personium/core/PersoniumCoreException.java#L766
> Fix description of PR400-AZ-0007
